### ISSUE TITLE
"objax.variable.VarCollection is not a valid JAX type" when creating a custom optimizer

### ISSUE THREAD

**Issue by RXZ2020** [google/objax#114]
Hi, I wish to create a custom optimizer to replace the 
`opt(lr=lr, grads=g)
`
line in the example https://github.com/google/objax/blob/master/examples/classify/img/cifar10_simple.py

Instead, I replaced it with 
```
for grad, p in zip(g, model_vars):
      p.value -= lr * grad   
```
and then supplied model.vars() as an argument to train_op. However, I received an error: objax.variable.VarCollection is not a valid JAX type. Can someone help me with this issue? Here is a minimal working example which reproduces the error. 

```
import random
import numpy as np
import tensorflow as tf
from objax.zoo.wide_resnet import WideResNet

# Data
(X_train, Y_train), (X_test, Y_test) = tf.keras.datasets.cifar10.load_data()
X_train = X_train.transpose(0, 3, 1, 2) / 255.0
X_test = X_test.transpose(0, 3, 1, 2) / 255.0

# Model
model = WideResNet(nin=3, nclass=10, depth=28, width=2)
#opt = objax.optimizer.Adam(model.vars())
predict = objax.Jit(lambda x: objax.functional.softmax(model(x, training=False)),
                    model.vars())
# Losses
def loss(x, label):
    logit = model(x, training=True)
    return objax.functional.loss.cross_entropy_logits_sparse(logit, label).mean()

gv = objax.GradValues(loss, model.vars())

def train_op(x, y, model_vars, lr):
    g, v = gv(x, y)
    for grad, p in zip(g, model_vars):
      p.value -= lr * grad   
    return v


# gv.vars() contains the model variables.
train_op = objax.Jit(train_op, gv.vars()) #I deleted opt.vars()

for epoch in range(30):
    # Train
    loss = []
    sel = np.arange(len(X_train))
    np.random.shuffle(sel)
    for it in range(0, X_train.shape[0], 64):
        loss.append(train_op(X_train[sel[it:it + 64]], Y_train[sel[it:it + 64]].flatten(), model.vars(), 4e-3 if epoch < 20 else 4e-4)) #I added model.vars() 
```

**Comment by david-berthelot** [comment]
In Objax, contrary to other JAX frameworks, you don't need to pass model variables around. They are stored in modules, and for functions they're only need when you JIT them.

In your particular example, you don't need to pass `model_vars` to `train_op`, you already do it in the `Jit` call.

```python
def train_op(x, y, lr):
    g, v = gv(x, y)
    for grad, p in zip(g, model_vars.subset(objax.TrainVar)):
      p.value -= lr * grad   
    return v
```

Check the SGD source code, it's 3 lines of code, basically you can copy it and make your own optimizer:
https://objax.readthedocs.io/en/latest/_modules/objax/optimizer/sgd.html#SGD

**Comment by RXZ2020** [comment]
Thanks for the fast reply. When I ran this code I received:
_ValueError: Direct assignment not allowed, use TrainRef to update a TrainVar._
I got the same error by replacing model_vars with model.vars() which I think are equivalent.

**Comment by RXZ2020** [comment]
I got it working by replacing 
`model_vars.subset(objax.TrainVar)`
with
`ModuleList(TrainRef(x) for x in model.vars().subset(TrainVar))`
and importing the associated modules 
```
from objax.module import Module, ModuleList
from objax.variable import TrainRef, TrainVar, VarCollection
```
However, I have two issues which is 1. this code is very slow because I'm not using Objax.Jit on the optimizer routine (took roughly 16 seconds for 1 epoch), 2. it is not very minimalistic. Do you have any suggestions?

**Comment by david-berthelot** [comment]
Oh right, yes `=` is disallow on `TrainVar` to avoid users accidentally writing a trainable variable.

For minimalism, you could use `assign` instead of `=`:
```python
def train_op(x, y, lr):
    g, v = gv(x, y)
    for grad, p in zip(g, model_vars.subset(objax.TrainVar)):
      p.assign(p.value - lr * grad)   
    return v
```

For performance, you simply need to JIT `train_op`, everything inside gets jitted.

**Comment by RXZ2020** [comment]
Thanks for your reply! I am still having some trouble however. After using,
```
    for grad, p in zip(g, model_vars.subset(objax.TrainVar)):
      p.assign(p.value - lr * grad) 
```
exactly as it appears, I received: _UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function. The functions being transformed should not save traced values to global state._

Is there a way to modify 
`train_op = objax.Jit(train_op, gv.vars())
`
to account for the optimizer?

**Comment by RXZ2020** [comment]
Thanks for your reply! I am still having some trouble however. After using,
```
def train_op(x, y, lr):
    g, v = gv(x, y)
    for grad, p in zip(g, model_vars.subset(objax.TrainVar)):
      p.assign(p.value - lr * grad)   
    return v
```
exactly as it appears, I received: _UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function. The functions being transformed should not save traced values to global state._

After fixing this problem I will try out jit(train_op(...)). However, is there a way to directly modify 
`train_op = objax.Jit(train_op, gv.vars())
`
to account for the optimizer?

**Comment by david-berthelot** [comment]
I updated my comment, check if it works.

**Comment by RXZ2020** [comment]
I've changed my code per your suggestion. Unfortunately now I have this error:
`TypeError: cannot convert dictionary update sequence element #0 to a sequence`

**Comment by david-berthelot** [comment]
Updated again.

**Comment by RXZ2020** [comment]
Thanks. This completely solves my question. 
Just as a suggestion (feel free to disagree here) it seems that this line 
`objax.ModuleList(objax.TrainRef(x) for x in model.vars().subset(objax.TrainVar))`
could be made more minimalistic somewhere down the line, or at least a bit more intuitive. 
All the user wants to do is to update the trainable variables in the model. 
Perhaps there should be a way to directly access them with minimal code and then just update them as usual
e.g., trainable_vars = trainable_vars + lr * gradient

**Comment by david-berthelot** [comment]
Well consider that Objax is object-oriented and an optimizer is meant to be an `objax.Module`. If you look at SGD it's just 3 lines of code:
https://objax.readthedocs.io/en/latest/_modules/objax/optimizer/sgd.html#SGD

On the other hand, if you're looking for a functional design, maybe pure JAX is what will suit you best or one of the functional frameworks out there (I mean they're pretty much all functional).

**Comment by david-berthelot** [comment]
Reopening since I'm experimenting with design changes to allow for the original code, e.g.:
```python
def train_op(x, y, lr):
    g, v = gv(x, y)
    for grad, p in zip(g, model_vars.subset(objax.TrainVar)):
      p.assign(p.value - lr * grad)   
    return v
```
