### ISSUE TITLE
losses and metrics

### ISSUE THREAD

**Issue by AakashKumarNain** [google/objax#12]
Are we looking to add `losses` and `metrics`? If yes, I can start working on it

**Comment by david-berthelot** [comment]
Yes we are, basically the library part is meant to grow, which can be a good opportunity for the community to contribute.
While the core should be pretty much self-contained at this point but again it's minimal, we can add some stuff that's wanted.

**Comment by AakashKumarNain** [comment]
Thanks. I will add some of the most commonly used metrics and losses for the start.
