### ISSUE TITLE
Question: difference between Flax and Objax

### ISSUE THREAD

**Issue by Borda** [google/objax#129]
This is just a question as I cross over Objax and [Flax](https://github.com/google/flax) today and both are google frameworks and both claim to be the deep learning framework in Jax. I noticed that the API is slightly different... Could you share some thoughts on the relation of these frameworks or eventual cooperation in a single user project?
Thank you 🐰

**Comment by AlexeyKurakin** [comment]
We will write and FAQ for JAX and will address this question there
Here is tracking issue on FAQ: https://github.com/google/objax/issues/139
