### ISSUE TITLE
Activation functions like Swish and Mish are absent.

### ISSUE THREAD

**Issue by iamharsha1999** [google/objax#225]
@AlexeyKurakin Hey activations such as mish and swish aren't available in objax.functional module. Would it be possible to add them like how they have done it with Pytorch ? (https://pytorch.org/docs/stable/generated/torch.nn.functional.mish.html#torch.nn.functional.mish)

**Comment by AlexeyKurakin** [comment]
`objax.function` is mainly intended to be a wrapper for various JAX functions.
It seems like swish activation is available as a JAX primitive: https://jax.readthedocs.io/en/latest/jax.nn.html
So if you're welcome to make a pull request to add swish to `objax.function.activations`
