### ISSUE TITLE
Cleanup and reformat examples directory

### ISSUE THREAD

**Issue by AlexeyKurakin** [google/objax#71]

**Comment by AlexeyKurakin** [comment]
Examples directory updated in PR #120

**Comment by AlexeyKurakin** [comment]
Last two things which needs to be done - update links/paths in RST documentation in following two files:
https://github.com/google/objax/blob/master/docs/source/examples.rst
https://github.com/google/objax/blob/master/docs/source/tutorials.rst

**Comment by schien1729** [comment]
I think this is done with PR #194
